# Generated by Django 3.2.3 on 2021-09-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
    ]
