# Generated by Django 3.2.3 on 2021-09-27 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_date']},
        ),
    ]
